:rotating_light: (remove warning implementation_imports by exporting segment_web.dart
la-haus/flutter-segment pull request #20
Opened 2022-03-31 16:18 UTC by T-moz

Lint: https://dart-lang.github.io/linter/lints/implementation_imports.html

2022-04-21 15:25 UTC, danielgomezrico commented on example/lib/generated_plugin_registrant.dart
> -import 'package:flutter_segment/src/segment_web.dart';
Why adding a file that exports the same import will fix the warning? is it the real solution for this?

2022-06-09 19:45 UTC, danielgomezrico commented on example/lib/generated_plugin_registrant.dart
> -import 'package:flutter_segment/src/segment_web.dart';
@T-moz Ping

2022-06-10 21:20 UTC, cdmunoz requested changes
This changes don't have any relationship with fixing the linter.
In addition, the code base is behind master and other changes that need to be updated to do a proper review.

2022-06-29 00:01 UTC, cdmunoz approved these changes
LGTM 👌🏻

2022-06-29 00:07 UTC, merged

2022-07-21 14:25 UTC, danielgomezrico commented
Fix https://github.com/la-haus/flutter-segment/issues/24